name: JVillage
description: A claim plugin designed for Project Poseidon
main: com.johnymuffin.jvillage.beta.JVillage
version: 1.0.0
authors:
  - JohnyMuffin
softdepend:
  - Fundamentals

commands:
  villageadmin:
    description: Village admin commands
    usage: /<command>
    aliases:
      - va
  village:
    description: Village player commands
    usage: /<command>
    aliases:
      - v